### ISSUE TITLE
fsevents and env issue on Windows

### ISSUE THREAD

**Issue by jgaro** [tagyoureit/nodejs-poolController-webClient#17]
webclient@6.1.0 trying to build on windows10. I see `Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`, which ends up throwing this error: `env NODE_ENV=production node dist/Server.js 'env' is not recognized as an internal or external command,`. I'm assuming this is related to how nodejs is building for the environment? Is there any way to either force it to use windows, or check out what dependencies might be throwing this?

**Comment by tagyoureit** [comment]
fsevents is an optional dependency and not related to the node environment variable.

Can you see this article:
https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows

Try either the powershell or cmd version to set the environment variable to production and it lmk if that works.

**Comment by jgaro** [comment]
I'm not completely sure that this is a cross-platform fix, but I was able to get it to work only after changing package.json to `"start:cached": "set NODE_ENV=production && node dist/Server.js",`. Setting windows env variables did not change anything for me. Happy to close this, or can test some other things if it's helpful?

**Comment by tagyoureit** [comment]
I have deprecated this project in favor of [dashPanel](https://github.com/rstrouse/nodejs-poolcontroller-dashPanel).  Rstrouse and I have been doing a ton of work and this project has fallen behind and it isn't worth the effort to keep two similar projects maintained.  If anything from this project is missing please request it in the other repo.
