### ISSUE TITLE
dependancies driving me crazy

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController-webClient#19]
webClient quits working after a few days, reboot seem to be the trigger but after a few days.

I remove the directory, reinstall git clone, npm i, and it works for a few days, rinse and repeat.

webClient in terminal appears to be working normal, just no webpage at ip:8080

Check dependancy with npm list and get;
npm ERR! peer dep missing: react@~16.12.0, required by react-horizontal-stacked-bar-chart@8.15.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-rangeslider@2.2.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by recompose@0.22.0

If I install these exact items I get like 10 more dependancies for later packages, when I install the later packages then I just have these three.

**Comment by tagyoureit** [comment]
You're describing two completely different problems.  There should be logs as to why webclient is quitting.  Installing dependencies should be a separate problem.  Maybe you can give some more details on each of these?  

And see my other comment about the port: https://github.com/tagyoureit/nodejs-poolController-webClient/issues/18#issuecomment-719161335

**Comment by miamijerry** [comment]
OK, re-installed webClient working again, same three dependancies listed;
npm list (post fresh install)
npm ERR! peer dep missing: react@~16.12.0, required by react-horizontal-stacked-bar-chart@8.15.2
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-rangeslider@2.2.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by recompose@0.22.0

But it is running

There are no logs in /home/pi/.npm/_logs from the date (yesterday) when the webclient ip:8080 stopped appearing.

How or where do I get logs for "ip:8080" issue?

**Comment by miamijerry** [comment]
OK, no reboots, just 12 hours later and no IP:8080 webpage anymore...

**Comment by tagyoureit** [comment]
> /home/pi/.npm/_logs
This is only the location for the logs for installation of dependencies (`npm i`) and not the logs for running the app.

How are you starting/running the njsPC-webclient app?

**Comment by miamijerry** [comment]
Originally the following entry in the /etc/rc.local file;
cd ~pi/nodejs-poolController-webClient
npm start

Currently starting by;
lxterminal -e sudo bash Start_webClient.sh

With Start_webClient.sh containing;
cd /home/pi/nodejs-poolController-webClient
npm start

Both of these start methods have the same problem of losing IP:8080

**Comment by tagyoureit** [comment]
It would be in the same place you are seeing the `PUT /chemController`.  Those are the logs.

**Comment by miamijerry** [comment]
Running current NEXT branch, so I will see if this issue persists

**Comment by tagyoureit** [comment]
I have deprecated this project in favor of [dashPanel](https://github.com/rstrouse/nodejs-poolcontroller-dashPanel).  Rstrouse and I have been doing a ton of work and this project has fallen behind and it isn't worth the effort to keep two similar projects maintained.  If anything from this project is missing please request it in the other repo.
