### ISSUE TITLE
server.js wrong case

### ISSUE THREAD

**Issue by LTrainExpress** [tagyoureit/nodejs-poolController-webClient#2]
3:52:08 PM - Starting compilation in watch mode...

3:52:23 PM - Found 0 errors. Watching for file changes.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/pi/nodejs-poolController-webClient/dist/Server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
^C

------------------------------------------------------------------------
pi@raspberrypi:~/nodejs-poolController-webClient/dist $ ls
Config.js  Config.js.map  server.js  server.js.map

**Comment by tagyoureit** [comment]
Wow... VERY strange.  It was named 'Server.ts' on my side but Git wasn't picking up as being different from 'server.ts'.  I had to delete the file and recreate it new with the new name.  I'll blame this on Git.  Thanks.

**Comment by LTrainExpress** [comment]
So the code refers to it in some spots as Server.js and others as server.js. So now the file is renamed but another part of the code broke XD

**Comment by tagyoureit** [comment]
Oy.  Somehow Server.js got pushed up.  I renamed it to Server.ts (pull it down or just rename it).  Other than that, it seems to be working fine on my end.  Can you delete the `./dist` directory and the run `npm start` again?  See if that helps.
