### ISSUE TITLE
PUT /chemController

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController-webClient#20]
Moved to "NEXT" on poolController and webClient Nov 2, 2020

Currently webClient terminal is flooded with;
PUT /chemController

While I have seen this in the past, restarting webClient used to resolve it

**Comment by miamijerry** [comment]
Might be low ORP value ??

**Comment by tagyoureit** [comment]
Due to the data structures it's easier to request all new data from the main app when an emit happens.  So this will be very chatty.  But nothing is broken.
