### ISSUE TITLE
Sunrise/ Sunset not working correctly 

### ISSUE THREAD

**Issue by rerouted** [tagyoureit/nodejs-poolController-webClient#21]
My pool controller controls some outlets outside.  During the holidays we have Christmas lights hooked to these outlets. I tried to set a schedule to have the outlets turn on at sunset but no matter the TZ it seems to always select 12:52p or 12:45am for sunrise. I have not looked at the code to see if this is just not implemented yet and hard coded values or if this is a bug. 

Either way great work on the 6.x release.

**Comment by tagyoureit** [comment]
I have deprecated this project in favor of [dashPanel](https://github.com/rstrouse/nodejs-poolcontroller-dashPanel).  Rstrouse and I have been doing a ton of work and this project has fallen behind and it isn't worth the effort to keep two similar projects maintained.  If anything from this project is missing please request it in the other repo.
