### ISSUE TITLE
Extra child devices and driver cleanup

### ISSUE THREAD

**Issue by MaxVonEvil** [tagyoureit/nodejs-poolController-webClient#23]
Hi Brad, Two questions for you, sir:

1) I have a single Intelliflow VS pump and a Rpi running the pool controller and webclient. I've installed the HE driver and everything works fine, however when installing the virtual device, a couple of extra child devices were created, which apparrently do not exist:
![image](https://user-images.githubusercontent.com/19863636/102191256-04a24480-3e6e-11eb-9949-d2aafde30564.png)
Is there a way to either remove these child devices or prevent them from being re-created if I start over?

2) since I don't have the equipment above (I do have heater and light, but those aren't connected to any Intelli*system. 
Is it safe to delete the driver code for the marked below (chlorinator, heater, lighting, chem) ?
![image](https://user-images.githubusercontent.com/19863636/102191669-94e08980-3e6e-11eb-8843-157a7cefcd8d.png)

Thanks a bunch,
Max

**Comment by tagyoureit** [comment]
Hi, yes, it's safe to delete them.  In the future, you'll want to post questions about HE in @bsileo's repo: https://github.com/bsileo/hubitat_poolcontroller
