### ISSUE TITLE
No ORP or PH reading in Webclient 6.1.1

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController-webClient#30]
After updating poolController to next 6.5.2, Dashpanel 0.0.1 and webClient to next 6.1.1
Noticed that webClient is not showing ORP and PH reading, warning are shown.
![Missing chemical reading](https://user-images.githubusercontent.com/8471168/111043182-2ed4b580-840f-11eb-9224-9be524634e12.JPG)

Terminal had an error, but on second run there was not errors. Still no ORP or PH readings
[Error.txt](https://github.com/tagyoureit/nodejs-poolController-webClient/files/6135470/Error.txt)

**Comment by tagyoureit** [comment]
Please switch over to [dashPanel](http://github.com/rstrouse/nodejs-poolcontroller-dashPanel/).  I'm likely not going to update webClient anymore.

We've done a lot of work on dashPanel + REM (relayEquipmentManager) and also it's fully compatibly with *Touch systems now and so it no longer makes sense to have two separate clients.

**Comment by miamijerry** [comment]
OK, Thanks
