### ISSUE TITLE
When using virtual controller, Date/Time field displays "Invalid Date"

### ISSUE THREAD

**Issue by jarrah42** [tagyoureit/nodejs-poolController-webClient#9]
Also, if you click on the "Invalid Date" button, it takes you to a blank screen.

**Comment by tagyoureit** [comment]
I pushed up a fix for this.  Virtual controller now uses the system (main app) time and will update every minute.

**Comment by tagyoureit** [comment]
I have deprecated this project in favor of [dashPanel](https://github.com/rstrouse/nodejs-poolcontroller-dashPanel).  Rstrouse and I have been doing a ton of work and this project has fallen behind and it isn't worth the effort to keep two similar projects maintained.  If anything from this project is missing please request it in the other repo.
